#!/bin/bash

# Tool to create HTML browseable version of the specifications.
# Requires raml2html (https://github.com/kevinrenskers/raml2html)
# (c) AMWA 2017


HTMLDIR=../docs/html-APIs

havecmd ()
{
    type $1 > /dev/null 2>&1
}

if ! havecmd raml2html; then
    echo "Please install raml2html"
    exit 1
fi

# In case script is run from elsewhere
cd $(dirname "${BASH_SOURCE[0]}")

# Proper behaviour when no glob match
shopt -s nullglob


if [ ! -e $HTMLDIR ]; then
    echo
    echo "Making HTML directory: $HTMLDIR..."
    mkdir $HTMLDIR
fi

for INFILE in *.raml
do
    echo
    echo "Found RAML file " $INFILE
    OUTFILE=$HTMLDIR/${INFILE%%raml}html
    echo "Generatng $OUTFILE..."
    raml2html $INFILE > $OUTFILE
done

echo
echo "Creating $HTMLDIR/README.md..."

cat > $HTMLDIR/README.md << 'EOF'
# NMOS IS-04 APIs

The APIs are formally specified in [RAML and JSON Schema](https://github.com/AMWA-TV/nmos-discovery-registration/APIs).  These HTML versions have been generated using raml2html.

[Node API](NodeAPI.html)

[Query API](QueryAPI.html)

[Registration API](RegistrationAPI.html)
EOF

echo
echo "Linting..."
jsonlint -v ../examples/*.json
echo ""
jsonlint -v schemas/*.json
